"""empty message

Revision ID: 6499bcacf1ee
Revises: 7155949b6787
Create Date: 2022-05-19 15:35:17.981322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6499bcacf1ee'
down_revision = '7155949b6787'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solicitations', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'solicitations', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'solicitations', type_='foreignkey')
    op.drop_column('solicitations', 'category_id')
    # ### end Alembic commands ###
