"""empty message

Revision ID: de22d740cbff
Revises: 
Create Date: 2022-05-19 00:53:41.742495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de22d740cbff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('url', sa.String(), nullable=True))
    op.drop_column('news', 'phoneNumber')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('phoneNumber', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('news', 'url')
    # ### end Alembic commands ###
